name: dz_bus_tracker
description: "DZ Bus Tracker – Scalable Flutter Front-End with Beautiful UI/UX & High Performance. (by Jugurtha-Green)"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  # Use a recent stable SDK constraint compatible with most packages
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.29.0"

# Application Dependencies
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Added for localization delegates
    sdk: flutter

  geolocator: ^14.0.0
  message_pack_dart: ^2.0.1
  http_parser: ^4.1.2

  # Core & Utility Packages
  cupertino_icons: ^1.0.8 # User provided
  equatable: ^2.0.7 # For value equality in BLoC states/events, Entities
  dartz: ^0.10.1 # For Functional Programming (Either type)
  get_it: ^8.0.3 # Service Locator for Dependency Injection
  shared_preferences: ^2.5.3 # Local key-value storage (Check pub.dev for absolute latest if needed)
  flutter_secure_storage: ^9.2.4 # Secure storage for tokens etc.
  connectivity_plus: ^6.1.3 # Check network status
  dio: ^5.8.0+1 # HTTP client
  logger: ^2.5.0 # App logging
  intl: ^0.20.2 # Internationalization & Date/Number formatting (Check pub.dev)
  timeago: ^3.2.2 # Relative time formatting (e.g., "5 minutes ago")
  mime: ^2.0.0 # Mime type lookup (for file uploads)
  path: ^1.9.1 # Path manipulation utilities
  collection: ^1.19.1 # Utility collections and functions (groupBy, etc.)
  rxdart: ^0.28.0 # For BehaviorSubject (advanced stream controllers)
  timezone: ^0.10.0 # Timezone database for local notifications (Check pub.dev)
  cached_network_image: ^3.4.1 # Display and cache network images
  image_picker: ^1.1.2 # Pick images from gallery/camera
  path_provider: ^2.1.5 # Find commonly used locations on the filesystem (used by image_picker etc)

  # State Management
  flutter_bloc: ^9.1.0 # BLoC pattern implementation
  bloc_concurrency: ^0.3.0 # Event transformers (restartable, droppable)

  # UI & Navigation
  go_router: ^15.0.0 # Declarative routing (Check pub.dev)
  smooth_page_indicator: ^1.2.1 # Animated page indicator (for onboarding)
  google_maps_flutter: ^2.12.1 # Google Maps integration (Check pub.dev)

  # Data Models & Serialization

  messagepack: ^0.2.1 # MessagePack serialization/deserialization (Check pub.dev)

  # Firebase (optional, uncomment if using)
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0 # Already added for local notifications

  ###freezed_annotation: ^3.0.0 # Annotations for freezed code generator
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0 # Annotations for json_serializable (Check pub.dev)
  permission_handler: ^11.3.1 # Permissions management (Check pub.dev)
# Development Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0 # Updated lints (Check pub.dev)

#  flutter_secure_storage_linux: ^2.0.1
#  flutter_secure_storage_macos: ^4.0.0
#  flutter_secure_storage_platform_interface: ^2.0.1
#  flutter_secure_storage_web: ^2.0.0
#  flutter_secure_storage_windows: ^4.0.0
#  material_color_utilities : ^0.12.0
#  vector_math: ^2.1.5
  lints: ^5.0.0
# Code Generation
  ###build_runner: ^2.4.15 # Runs code generators
  ###freezed: ^3.0.6 # Code generator for data classes/unions
  ###json_serializable: ^6.9.4 # Code generator for JSON serialization
  freezed: ^2.3.5
  build_runner: ^2.3.3
  json_serializable: ^6.6.2

# Flutter specific configuration
flutter:
  uses-material-design: true

  # Declare Assets
  assets:
    - assets/images/ # Base images
    - assets/images/backgrounds/ # Background images
    - assets/images/onboarding/ # Onboarding illustrations
    - assets/images/illustrations/ # General illustrations
    - assets/images/map/ # Map marker icons
    - assets/icons/ # SVG or PNG icons
    - assets/map_styles/ # JSON map styles
    # - assets/i18n/ # Only if using manual JSON loading for i18n

  # Declare Fonts (Example using Poppins)
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        # Add Italic variants if needed
        # - asset: assets/fonts/Poppins-RegularItalic.ttf
        #   style: italic

# Configuration for flutter_gen_l10n (if using .arb files)
flutter_intl:
  enabled: true # Assuming you use flutter_intl or similar tool
    # main_locale: fr # Optional: specify default locale here too
    # arb_dir: lib/i18n/arb # Default location often works
    # output_dir: lib/generated # Default location often works
        #   style: italic