// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqRoCH4Ut0440vFjovwvvqGz1yfh8N_H0',
    appId: '1:715316138522:web:78df3df970d7b36d3a37a3',
    messagingSenderId: '715316138522',
    projectId: 'dz-bus-tracker-jugu',
    authDomain: 'dz-bus-tracker-jugu.firebaseapp.com',
    storageBucket: 'dz-bus-tracker-jugu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqRoCH4Ut0440vFjovwvvqGz1yfh8N_H0',
    appId: '1:715316138522:android:78df3df970d7b36d3a37a3',
    messagingSenderId: '715316138522',
    projectId: 'dz-bus-tracker-jugu',
    storageBucket: 'dz-bus-tracker-jugu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqRoCH4Ut0440vFjovwvvqGz1yfh8N_H0',
    appId: '1:715316138522:ios:78df3df970d7b36d3a37a3',
    messagingSenderId: '715316138522',
    projectId: 'dz-bus-tracker-jugu',
    iosClientId: '715316138522-abcd1234.apps.googleusercontent.com',
    storageBucket: 'dz-bus-tracker-jugu.firebasestorage.app',
    iosBundleId: 'com.jugurtha_green.dz_bus_tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqRoCH4Ut0440vFjovwvvqGz1yfh8N_H0',
    appId: '1:715316138522:ios:78df3df970d7b36d3a37a3',
    messagingSenderId: '715316138522',
    projectId: 'dz-bus-tracker-jugu',
    iosClientId: '715316138522-abcd1234.apps.googleusercontent.com',
    storageBucket: 'dz-bus-tracker-jugu.firebasestorage.app',
    iosBundleId: 'com.jugurtha_green.dz_bus_tracker',
  );
}